import { Platform, StyleSheet } from 'react-native';
import { ThemeColors } from '../../constants/theme';

export const getBankAccountStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: 12,
    paddingBottom: 20,
  },
  idText: {
    fontSize: 12,
    fontWeight: '700',
    color: isDark ? '#94a3b8' : '#64748b',
  },
  primaryCellText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  cellText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionBtn: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalBox: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    width: Platform.select({ web: '55%', default: '94%' }),
    maxWidth: 650,
    maxHeight: '85%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  modalBody: {
    padding: 16,
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 10,
  },
  field: {
    marginBottom: 12,
  },
  formRow: {
    flexDirection: 'row',
    gap: 10,
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 4,
  },
  input: {
    backgroundColor: isDark ? '#090d16' : '#f8fafc',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.textPrimary,
  },
  userChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
    marginRight: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  userChipActive: {
    backgroundColor: colors.primaryDark,
    borderColor: colors.primaryDark,
  },
  userChipText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  userChipTextActive: {
    color: '#ffffff',
  },
  calcBox: {
    backgroundColor: isDark ? '#261a02' : '#fefce8',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#fef08a',
    marginTop: 4,
  },
  calcBoxTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: isDark ? '#fbbf24' : '#854d0e',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  cancelBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cancelBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  saveBtn: {
    backgroundColor: colors.primaryDark,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
  },
  saveBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },
  statusToggleRow: {
    flexDirection: 'row',
    gap: 4,
  },
  statusBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 6,
    backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
  },
  statusBtnActive: {
    backgroundColor: colors.primaryDark,
  },
  statusBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  statusBtnTextActive: {
    color: '#ffffff',
  },
  detailSafeArea: {
    flex: 1,
    backgroundColor: isDark ? '#0c2238' : '#ddf4fe',
  },
  detailContainer: {
    flex: 1,
    backgroundColor: isDark ? '#090d16' : '#ffffff',
    maxWidth: 600,
    width: '100%',
    alignSelf: 'center',
  },
  detailHeaderBanner: {
    backgroundColor: isDark ? '#0c2238' : '#ddf4fe',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  detailBackBtn: {
    padding: 4,
    marginLeft: -4,
  },
  detailHeaderTitleCol: {
    flex: 1,
  },
  detailHeaderTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
    letterSpacing: -0.2,
  },
  detailHeaderSubtitle: {
    fontSize: 12,
    color: isDark ? '#94a3b8' : '#64748b',
    marginTop: 2,
  },
  detailScroll: {
    flex: 1,
    backgroundColor: isDark ? '#090d16' : '#ffffff',
  },
  detailScrollContent: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 24,
  },
  overviewCard: {
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: isDark ? '#1e293b' : '#e2e8f0',
    padding: 16,
  },
  overviewTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  bankIconSquare: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: isDark ? 'rgba(2, 132, 199, 0.2)' : '#e0f2fe',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bankNameCol: {
    flex: 1,
  },
  detailBankNameText: {
    fontSize: 14.5,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
  },
  detailAccountTypeText: {
    fontSize: 12,
    color: isDark ? '#94a3b8' : '#64748b',
    marginTop: 2,
  },
  activeBadgePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: isDark ? 'rgba(22, 163, 74, 0.2)' : '#dcfce7',
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: 12,
  },
  activeBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#16a34a',
  },
  accNumberLabel: {
    fontSize: 11.5,
    color: isDark ? '#94a3b8' : '#64748b',
    marginTop: 14,
  },
  accNumberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  accNumberVal: {
    fontSize: 16,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
    letterSpacing: 1,
  },
  eyeBtn: {
    padding: 4,
  },
  overviewDivider: {
    height: 1,
    backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
    marginVertical: 14,
  },
  holderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  holderAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: isDark ? 'rgba(2, 132, 199, 0.2)' : '#e0f2fe',
    alignItems: 'center',
    justifyContent: 'center',
  },
  holderAvatarText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0284c7',
  },
  holderInfoCol: {
    flex: 1,
  },
  holderNameText: {
    fontSize: 13,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
  },
  holderSubText: {
    fontSize: 11.5,
    color: isDark ? '#94a3b8' : '#64748b',
    marginTop: 1,
  },
  loanLimitCard: {
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: isDark ? '#1e293b' : '#e2e8f0',
    padding: 16,
    marginTop: 14,
  },
  loanLimitHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  loanLimitTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
  },
  loanLimitPercent: {
    fontSize: 11.5,
    color: isDark ? '#94a3b8' : '#64748b',
  },
  limitTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: isDark ? '#1e293b' : '#e2e8f0',
    marginVertical: 10,
    overflow: 'hidden',
  },
  limitFill: {
    height: '100%',
    backgroundColor: '#0284c7',
    borderRadius: 3,
  },
  limitMetricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  limitMetricCol: {
    flex: 1,
  },
  limitMetricLabel: {
    fontSize: 10.5,
    color: isDark ? '#94a3b8' : '#64748b',
  },
  limitMetricVal: {
    fontSize: 13,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
    marginTop: 2,
  },
  limitHelperText: {
    fontSize: 10.5,
    color: isDark ? '#94a3b8' : '#64748b',
    marginTop: 10,
  },
  sectionHeaderTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: isDark ? '#cbd5e1' : '#0f172a',
    marginTop: 18,
    marginBottom: 8,
  },
  detailsCard: {
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: isDark ? '#1e293b' : '#e2e8f0',
    paddingHorizontal: 16,
    paddingVertical: 4,
  },
  detailTableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#1e293b' : '#f1f5f9',
  },
  tableKeyText: {
    fontSize: 12,
    color: isDark ? '#94a3b8' : '#64748b',
  },
  tableValText: {
    fontSize: 12,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
  },
  documentCard: {
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: isDark ? '#1e293b' : '#e2e8f0',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  docIconSquare: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docTextCol: {
    flex: 1,
  },
  docTitleText: {
    fontSize: 13,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
  },
  docSubText: {
    fontSize: 11,
    color: isDark ? '#94a3b8' : '#64748b',
    marginTop: 2,
  },
  noLoansCard: {
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: isDark ? '#1e293b' : '#e2e8f0',
    padding: 14,
  },
  noLoansText: {
    fontSize: 12,
    color: isDark ? '#94a3b8' : '#64748b',
    textAlign: 'center',
  },
  loanItemCard: {
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: isDark ? '#1e293b' : '#e2e8f0',
    padding: 14,
    marginBottom: 8,
  },
  loanItemTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  loanItemNumber: {
    fontSize: 13,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
  },
  loanItemSubText: {
    fontSize: 11.5,
    color: isDark ? '#94a3b8' : '#64748b',
    marginTop: 4,
  },
  detailBottomBar: {
    backgroundColor: isDark ? '#090d16' : '#ffffff',
    borderTopWidth: 1,
    borderTopColor: isDark ? '#1e293b' : '#e2e8f0',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  editAccountBtn: {
    borderWidth: 1,
    borderColor: isDark ? '#f8fafc' : '#0f172a',
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 10,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  editAccountBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
  },
});
