import { useMemo } from 'react';
import { Platform, StyleSheet, useWindowDimensions } from 'react-native';
import { ThemeColors } from '../../constants/theme';
import { useTheme } from '../../context/ThemeContext';

export const getOrnamentsStyles = (colors: ThemeColors, isDark: boolean, isCompact: boolean = false) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: isDark ? '#090d16' : '#d8edfa',
  },
  subScreenContainer: {
    flex: 1,
    backgroundColor: isDark ? '#090d16' : '#ffffff',
  },
  container: {
    flex: 1,
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: isDark ? '#090d16' : '#ffffff',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
    maxWidth: 680,
    width: '100%',
    alignSelf: 'center',
    backgroundColor: isDark ? '#090d16' : '#ffffff',
  },
  listTopSection: {
    backgroundColor: isDark ? '#0f172a' : '#d8edfa',
    paddingHorizontal: 16,
    paddingTop: isCompact ? 4 : 10,
    paddingBottom: 2,
  },
  searchCardWrapper: {
    position: 'relative',
    paddingTop: 4,
    paddingBottom: 10,
    paddingHorizontal: 16,
    backgroundColor: isDark ? '#0f172a' : '#d8edfa',
  },
  sheetBackground: {
    position: 'absolute',
    top: isCompact ? 52 : 64,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: isDark ? '#090d16' : '#ffffff',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  cardsScrollContainer: {
    flex: 1,
    backgroundColor: isDark ? '#090d16' : '#ffffff',
  },
  cardsScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 80,
    maxWidth: 680,
    width: '100%',
    alignSelf: 'center',
    backgroundColor: isDark ? '#090d16' : '#ffffff',
  },

  // Headers
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: isCompact ? 8 : 16,
    paddingTop: 4,
  },
  headerLeft: {
    flex: 1,
  },
  screenTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: isDark ? '#f8fafc' : '#0d172a',
    letterSpacing: -0.4,
  },
  screenSubtitle: {
    fontSize: 13,
    color: isDark ? '#94a3b8' : '#475569',
    marginTop: 2,
  },
  headerRight: {
    alignItems: 'flex-end',
    paddingLeft: 10,
  },
  totalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: isDark ? '#94a3b8' : '#334155',
  },
  totalNumber: {
    fontSize: 30,
    fontWeight: '800',
    color: '#0284c7',
    marginTop: -2,
  },

  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? 14 : 10,
    paddingBottom: 12,
    backgroundColor: isDark ? '#0f172a' : '#d8edfa',
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#1e293b' : '#bfe0f2',
  },
  headerBackBtn: {
    padding: 6,
    marginRight: 6,
  },
  headerTitles: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: isDark ? '#f8fafc' : '#0d172a',
    letterSpacing: -0.2,
  },
  headerSubtitle: {
    fontSize: 12,
    color: isDark ? '#94a3b8' : '#64748b',
    marginTop: 1,
  },
  // Search & Filter Card (Unified Card matching mockup)
  searchFilterCard: {
    backgroundColor: isDark ? '#1e293b' : '#ffffff',
    borderRadius: 20,
    padding: isCompact ? 10 : 14,
    maxWidth: 680,
    width: '100%',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: isDark ? '#334155' : 'rgba(226, 232, 240, 0.8)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: isDark ? 0.25 : 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: isCompact ? 8 : 12,
  },
  boxySearchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#e2e8f0',
    paddingHorizontal: 12,
    height: isCompact ? 44 : 52,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 13.5,
    color: isDark ? '#f8fafc' : '#0f172a',
    paddingVertical: 8,
  },
  clearBtn: {
    padding: 4,
    marginRight: 2,
  },
  filterIconBtn: {
    padding: 8,
    marginLeft: 10,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterIconBtnActive: {
    backgroundColor: isDark ? 'rgba(2, 132, 199, 0.15)' : '#e0f2fe',
  },

  // Filter Pills (Inside Card)
  filterPillsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 2,
  },
  filterPill: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterPillActive: {
    backgroundColor: '#0284c7',
    borderColor: '#0284c7',
  },
  filterPillText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: isDark ? '#cbd5e1' : '#334155',
  },
  filterPillTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },

  // Cards List
  cardsList: {
    gap: isCompact ? 8 : 12,
  },
  listCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: isDark ? '#1e293b' : '#f1f5f9',
    padding: isCompact ? 10 : 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: isDark ? 0.2 : 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardLeftCol: {
    alignItems: 'center',
    marginRight: 12,
  },
  thumbContainer: {
    width: 72,
    height: 72,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
  },
  thumbImage: {
    width: '100%',
    height: '100%',
  },
  thumbPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDark ? '#1e293b' : '#f0f9ff',
  },
  loanBox: {
    alignItems: 'center',
    marginTop: 4,
  },
  loanLabel: {
    fontSize: 10,
    color: isDark ? '#94a3b8' : '#64748b',
  },
  loanVal: {
    fontSize: 10,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
  },

  cardCenterCol: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingTop: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  listCardTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: isDark ? '#f8fafc' : '#0d172a',
    flex: 1,
    marginRight: 6,
  },

  cardIdText: {
    fontSize: 11,
    color: isDark ? '#94a3b8' : '#64748b',
    marginBottom: 8,
  },
  specsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  specsText: {
    fontSize: 11,
    color: isDark ? '#94a3b8' : '#475569',
  },
  cardStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  statGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statWeightText: {
    fontSize: 12,
    fontWeight: '700',
    color: isDark ? '#cbd5e1' : '#334155',
  },
  statPriceCurrency: {
    fontSize: 12,
    fontWeight: '800',
    color: isDark ? '#f8fafc' : '#0d172a',
    marginRight: 2,
  },
  statPriceText: {
    fontSize: 13,
    fontWeight: '800',
    color: isDark ? '#f8fafc' : '#0d172a',
  },
  cardRightCol: {
    paddingLeft: 6,
  },

  fabBtn: {
    position: 'absolute',
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#0284c7',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0284c7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 15,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0d172a',
    marginTop: 12,
  },
  emptySubtitle: {
    fontSize: 12,
    color: isDark ? '#94a3b8' : '#64748b',
    marginTop: 4,
  },

  // Stepper Styles
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#1e293b' : '#e2e8f0',
  },
  stepItem: {
    alignItems: 'center',
    gap: 4,
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: isDark ? '#334155' : '#cbd5e1',
    backgroundColor: isDark ? '#1e293b' : '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepCircleActive: {
    borderColor: '#0284c7',
    backgroundColor: '#0284c7',
  },
  stepCircleDone: {
    borderColor: '#0284c7',
    backgroundColor: '#0284c7',
  },
  stepNum: {
    fontSize: 12,
    fontWeight: '700',
    color: isDark ? '#94a3b8' : '#64748b',
  },
  stepNumActive: {
    color: '#ffffff',
  },
  stepLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: isDark ? '#94a3b8' : '#64748b',
  },
  stepLabelActive: {
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0d172a',
  },
  stepLine: {
    width: 44,
    height: 2,
    backgroundColor: isDark ? '#334155' : '#e2e8f0',
    marginBottom: 16,
    marginHorizontal: 6,
  },
  stepLineActive: {
    backgroundColor: '#0284c7',
  },

  // Gallery
  gallerySection: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  mainImageContainer: {
    flex: 1,
    height: 240,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#0f172a',
    position: 'relative',
  },
  mainImage: {
    width: '100%',
    height: '100%',
  },
  arrowBtn: {
    position: 'absolute',
    top: '50%',
    marginTop: -16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
  },
  arrowBtnLeft: { left: 10 },
  arrowBtnRight: { right: 10 },
  thumbnailsColumn: {
    width: 78,
    gap: 8,
  },
  thumbBox: {
    height: 52,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  thumbBoxActive: {
    borderColor: '#0284c7',
  },
  thumbImg: {
    width: '100%',
    height: '100%',
  },
  addPhotoDashedBtn: {
    height: 52,
    borderRadius: 12,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#0284c7',
    backgroundColor: isDark ? 'rgba(2, 132, 199, 0.1)' : '#f0f9ff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 2,
  },
  addPhotoText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#0284c7',
    marginTop: 2,
    textAlign: 'center',
  },
  noPhotoCard: {
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: isDark ? '#1e293b' : '#e2e8f0',
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  noPhotoIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: isDark ? '#1e293b' : '#e0f2fe',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  noPhotoTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0d172a',
    marginBottom: 4,
    textAlign: 'center',
  },
  noPhotoSubtitle: {
    fontSize: 12,
    color: isDark ? '#94a3b8' : '#64748b',
    textAlign: 'center',
    marginBottom: 16,
    maxWidth: 280,
  },
  noPhotoUploadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0284c7',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
  },
  noPhotoUploadBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },

  // Title Row
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  titleLeft: {
    flex: 1,
    paddingRight: 10,
  },
  ornamentTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: isDark ? '#f8fafc' : '#0d172a',
    letterSpacing: -0.2,
  },
  idCopyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
  },
  ornamentIdText: {
    fontSize: 13,
    fontWeight: '600',
    color: isDark ? '#94a3b8' : '#64748b',
  },
  // Card Structure
  card: {
    backgroundColor: isDark ? '#0f172a' : '#ffffff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: isDark ? '#1e293b' : '#e2e8f0',
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: isDark ? 0.2 : 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    marginBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? '#1e293b' : '#e2e8f0',
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  iconBox: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: isDark ? '#1e293b' : '#e0f2fe',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: isDark ? '#f8fafc' : '#0d172a',
  },
  cardSubtitle: {
    fontSize: 11,
    color: isDark ? '#94a3b8' : '#64748b',
    marginTop: 1,
  },
  quantityBox: { alignItems: 'flex-end' },
  quantityLabel: { fontSize: 11, color: isDark ? '#94a3b8' : '#64748b' },
  quantityValue: { fontSize: 15, fontWeight: '800', color: isDark ? '#f8fafc' : '#0d172a' },

  weightGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 0,
  },
  weightCol: { flex: 1, alignItems: 'flex-start' },
  weightLabel: { fontSize: 11, color: isDark ? '#94a3b8' : '#64748b', marginBottom: 4 },
  netWeightLabel: { color: isDark ? '#f8fafc' : '#000000', fontWeight: '700' },
  weightValue: { fontSize: 13, fontWeight: '800', color: isDark ? '#f8fafc' : '#0d172a' },
  netWeightValue: { color: isDark ? '#f8fafc' : '#000000' },

  tableRows: { gap: 10 },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 3,
  },
  rowLabel: { fontSize: 13, color: isDark ? '#94a3b8' : '#64748b' },
  rowValueBold: { fontSize: 13, fontWeight: '800', color: isDark ? '#f8fafc' : '#0d172a' },
  verifiedRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  verifiedText: { fontSize: 13, fontWeight: '700', color: '#16a34a' },
  appreciationPctText: { fontSize: 12, fontWeight: '700', color: '#16a34a', marginTop: 1 },

  fieldGroup: { marginBottom: 12 },
  inputLabel: { fontSize: 12, fontWeight: '600', color: isDark ? '#cbd5e1' : '#334155', marginBottom: 6 },
  requiredStar: { color: '#ef4444' },
  textInput: {
    backgroundColor: isDark ? '#1e293b' : '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#e2e8f0',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: isDark ? '#f8fafc' : '#0f172a',
    outlineWidth: 0,
  },
  twoColRow: { flexDirection: 'row', gap: 12 },
  dropdownInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: isDark ? '#1e293b' : '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#e2e8f0',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dropdownValue: { fontSize: 13, fontWeight: '600', color: isDark ? '#f8fafc' : '#0f172a' },

  unitInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? '#1e293b' : '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#e2e8f0',
    overflow: 'hidden',
  },
  unitInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: isDark ? '#f8fafc' : '#0f172a',
    outlineWidth: 0,
  },
  unitBadge: {
    backgroundColor: isDark ? '#0f172a' : '#f1f5f9',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderLeftWidth: 1,
    borderLeftColor: isDark ? '#334155' : '#e2e8f0',
  },
  unitBadgeText: { fontSize: 12, fontWeight: '700', color: isDark ? '#94a3b8' : '#64748b' },
  readonlyInputBox: {
    backgroundColor: isDark ? 'rgba(148, 163, 184, 0.12)' : '#e9edf5',
    borderColor: isDark ? '#334155' : '#d5dbe7',
  },
  readonlyUnitBadge: {
    backgroundColor: isDark ? 'rgba(148, 163, 184, 0.18)' : '#e2e7f0',
    borderLeftColor: isDark ? '#334155' : '#d5dbe7',
  },
  readonlyInputText: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    fontWeight: '700',
    color: isDark ? '#f8fafc' : '#0f172a',
  },
  labelWithInfo: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 6 },
  autoCalcRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  autoCalcBadge: {
    backgroundColor: isDark ? 'rgba(16, 185, 129, 0.15)' : '#e2f5ec',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  autoCalcBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: isDark ? '#34d399' : '#00b575',
  },
  autoCalcText: { fontSize: 10, fontWeight: '700', color: '#16a34a', marginTop: 3 },

  liveRateBadge: {
    backgroundColor: isDark ? '#1e293b' : '#f8fafc',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#e2e8f0',
    paddingHorizontal: 10,
    paddingVertical: 6,
    minWidth: 115,
  },
  liveRateTitle: {
    fontSize: 10,
    fontWeight: '500',
    color: isDark ? '#94a3b8' : '#64748b',
  },
  liveRateSubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  liveRateDotWithPurity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  liveRateGreenDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#10b981',
  },
  liveRatePurityText: {
    fontSize: 10,
    fontWeight: '600',
    color: isDark ? '#94a3b8' : '#64748b',
  },
  liveRateValue: {
    fontSize: 13,
    fontWeight: '800',
    color: isDark ? '#f8fafc' : '#0d172a',
    marginTop: 2,
  },

  prefixSuffixBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? '#1e293b' : '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#e2e8f0',
    paddingHorizontal: 12,
  },
  prefixText: { fontSize: 13, fontWeight: '700', color: isDark ? '#94a3b8' : '#64748b', marginRight: 6 },
  prefixInput: { flex: 1, paddingVertical: 10, fontSize: 13, fontWeight: '700', color: isDark ? '#f8fafc' : '#0f172a', outlineWidth: 0 },
  suffixText: { fontSize: 12, fontWeight: '600', color: isDark ? '#94a3b8' : '#64748b', marginLeft: 6 },

  calcGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 8 },
  calcTile: {
    width: '48%',
    backgroundColor: isDark ? '#1e293b' : '#f8fafc',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#e2e8f0',
    padding: 10,
  },
  calcTileTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  calcTileLabel: { fontSize: 10, fontWeight: '600', color: isDark ? '#94a3b8' : '#64748b', flex: 1 },
  calcTileValue: { fontSize: 13, fontWeight: '800', color: isDark ? '#f8fafc' : '#0d172a' },
  appreciationTileValue: { color: '#16a34a' },
  calcTileSub: { fontSize: 9, color: isDark ? '#94a3b8' : '#64748b', marginTop: 2 },

  photosRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 6, marginBottom: 12 },
  photoThumbWrapper: {
    width: 80,
    height: 80,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#e2e8f0',
  },
  photoThumbImg: { width: '100%', height: '100%' },
  photoRemoveBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.65)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addPhotoBox: {
    width: 80,
    height: 80,
    borderRadius: 12,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#0284c7',
    backgroundColor: isDark ? 'rgba(2, 132, 199, 0.1)' : '#f0f9ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addPhotoBoxText: { fontSize: 10, fontWeight: '700', color: '#0284c7', marginTop: 4 },
  calloutBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDark ? 'rgba(2, 132, 199, 0.1)' : '#f0f9ff',
    borderWidth: 1,
    borderColor: '#bae6fd',
    borderRadius: 10,
    padding: 10,
  },
  calloutText: { fontSize: 11, color: '#0284c7', fontWeight: '600', flex: 1 },
  multilineArea: { minHeight: 64, textAlignVertical: 'top' },
  charCounter: { fontSize: 10, color: '#94a3b8', textAlign: 'right', marginTop: 3 },

  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0284c7',
    paddingVertical: 12,
    borderRadius: 12,
  },
  primaryBtnText: { fontSize: 14, fontWeight: '700', color: '#ffffff' },
  actionsRow: { flexDirection: 'row', gap: 12 },
  backButtonSecondary: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: isDark ? '#1e293b' : '#ffffff',
    borderWidth: 1,
    borderColor: isDark ? '#334155' : '#cbd5e1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonSecondaryText: { fontSize: 13, fontWeight: '700', color: isDark ? '#f8fafc' : '#0f172a' },
});

/** Themed Ornaments-screen styles shared by the list, details and wizard views. */
export function useOrnamentsStyles() {
  const { colors, isDark } = useTheme();
  const { height } = useWindowDimensions();
  // Short phones only fit ~2 cards under the header, so tighten the vertical spacing there.
  const isCompact = height < 700;
  const styles = useMemo(() => getOrnamentsStyles(colors, isDark, isCompact), [colors, isDark, isCompact]);
  return { styles, colors, isDark };
}
