import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../constants/theme';

export const getStyles = (colors: ThemeColors, isDark: boolean) => StyleSheet.create({
  screenRoot: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
  },
  syncNoticePill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: isDark ? '#1e293b' : '#fefce8',
    borderColor: isDark ? '#334155' : '#e0f2fe',
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  syncNoticeText: {
    fontSize: 12,
    fontWeight: '700',
    color: isDark ? '#38bdf8' : '#0369a1',
  },
  readOnlyNoticeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: isDark ? 'rgba(56, 189, 248, 0.15)' : '#f0f9ff',
    borderColor: isDark ? 'rgba(56, 189, 248, 0.4)' : '#bae6fd',
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  readOnlyNoticeText: {
    flex: 1,
    fontSize: 12,
    color: isDark ? '#bae6fd' : '#0369a1',
    lineHeight: 16,
  },
  actionCardDisabled: {
    opacity: 0.75,
  },
  offlineNoticeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: isDark ? '#082f49' : '#fefce8',
    borderColor: isDark ? '#075985' : '#bae6fd',
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 14,
    gap: 8,
  },
  offlineNoticeText: {
    fontSize: 12,
    fontWeight: '600',
    color: isDark ? '#38bdf8' : '#0369a1',
    flex: 1,
  },
  offlineRetryPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: isDark ? '#0c4a6e' : '#e0f2fe',
    borderWidth: 1,
    borderColor: isDark ? '#075985' : '#0ea5e9',
  },
  offlineRetryPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: isDark ? '#38bdf8' : '#0369a1',
  },
  offlineEmptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 24,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 20,
  },
  offlineIconCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: isDark ? '#082f49' : '#e0f2fe',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  offlineEmptyTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 8,
    textAlign: 'center',
  },
  offlineEmptySub: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 20,
    maxWidth: 300,
  },
  offlineMainRetryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: isDark ? '#0284c7' : colors.primaryDark,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    elevation: 2,
  },
  offlineMainRetryBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  content: {
    padding: 16,
    paddingBottom: 80,
    width: '100%',
  },
  contentDesktop: {
    paddingHorizontal: 28,
    paddingVertical: 20,
    maxWidth: '100%',
    alignSelf: 'stretch',
  },

  // ─── RATES CARD ───
  goldRatesCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: 180,
  },
  cardHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  goldBadgeIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: isDark ? '#0c4a6e' : '#e0f2fe',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  cardSectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  cityPill: {
    backgroundColor: isDark ? '#0c4a6e' : '#e0f2fe',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    flexShrink: 0,
  },
  cityPillText: {
    fontSize: 10,
    fontWeight: '700',
    color: isDark ? '#38bdf8' : '#0369a1',
  },
  dateLabel: {
    fontSize: 11,
    color: colors.textMuted,
    flexShrink: 0,
  },

  // ─── RATES LAYOUTS (MOBILE VS DESKTOP) ───
  ratesMobileContainer: {
    gap: 10,
  },
  ratesTwoColRow: {
    flexDirection: 'row',
    gap: 10,
  },
  ratesGridRow: {
    flexDirection: 'row',
    gap: 10,
  },
  rateBox: {
    flex: 1,
    backgroundColor: isDark ? '#111827' : '#f8fafc',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  rateBoxFeatured: {
    backgroundColor: isDark ? '#082f49' : '#f0f9ff',
    borderColor: colors.primary,
    borderWidth: 1.5,
  },
  rateBoxHero: {
    padding: 14,
  },
  heroHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  rateBoxHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  rateKarat: {
    fontSize: 11.5,
    fontWeight: '700',
    color: colors.textSecondary,
    flex: 1,
  },
  rateKaratFeatured: {
    fontSize: 13,
    fontWeight: '800',
    color: isDark ? '#38bdf8' : colors.primaryDark,
  },
  miniBadge: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
    flexShrink: 0,
  },
  miniBadgeText: {
    fontSize: 9.5,
    fontWeight: '700',
  },
  rateAmount: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.textPrimary,
    letterSpacing: -0.3,
  },
  rateAmountFeatured: {
    fontSize: 19,
    color: isDark ? '#38bdf8' : colors.primaryDark,
  },
  rateUnit: {
    fontSize: 10.5,
    color: colors.textMuted,
    marginBottom: 6,
  },
  rateUnitHero: {
    fontSize: 13,
    color: colors.textMuted,
    marginBottom: 2,
  },
  heroAmountRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
  },
  sovereignBox: {
    backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 5,
    marginTop: 2,
  },
  sovereignText: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSecondary,
  },

  // ─── VALUATION ───
  sectionHeading: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  valGrid: {
    gap: 12,
    marginBottom: 20,
  },
  valGridRow: {
    flexDirection: 'row',
  },
  valCard: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  valCardSuccess: {
    backgroundColor: isDark ? '#052210' : '#f0fdf4',
    borderColor: isDark ? '#14532d' : '#bbf7d0',
  },
  valCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  valTitle: {
    fontSize: 11.5,
    fontWeight: '700',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    flex: 1,
  },
  valIconBox: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  valAmount: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  valBadge: {
    backgroundColor: isDark ? '#1e293b' : '#e0f2fe',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  valBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: isDark ? '#38bdf8' : '#0369a1',
  },

  // ─── METRICS GRID (2x2 on Mobile, 4 in a row on Desktop) ───
  metricsGridDesktop: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
    width: '100%',
  },
  metricsGridMobile: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
    marginBottom: 20,
    width: '100%',
  },
  metricCardDesktop: {
    flex: 1,
    minWidth: 0,
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  metricCardMobile: {
    width: '48.5%',
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  metricTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  metricIconBox: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: isDark ? '#0c4a6e' : '#e0f2fe',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  metricVal: {
    fontSize: 19,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  metricLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
    marginTop: 2,
    flex: 1,
  },
  metricHint: {
    fontSize: 10.5,
    color: colors.textMuted,
    marginTop: 2,
  },

  // ─── BANK UTILIZATION ───
  bankUtilCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 20,
  },
  bankUtilHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  bankUtilTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  bankUtilSubText: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  utilPill: {
    backgroundColor: isDark ? '#082f49' : '#e0f2fe',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    flexShrink: 0,
  },
  utilPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: isDark ? '#38bdf8' : '#0284c7',
  },
  utilAmountsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  utilAmountLabel: {
    fontSize: 11,
    color: colors.textMuted,
  },
  utilAmountVal: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
    marginTop: 2,
  },
  barBg: {
    height: 10,
    backgroundColor: isDark ? '#1e293b' : '#f1f5f9',
    borderRadius: 5,
    overflow: 'hidden',
    marginBottom: 10,
  },
  barFill: {
    height: '100%',
    backgroundColor: isDark ? '#0284c7' : colors.primaryDark,
    borderRadius: 5,
  },
  utilFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bankUtilSub: {
    fontSize: 12,
    color: colors.textSecondary,
    flex: 1,
  },

  // ─── QUICK ACTIONS GRID (4-IN-A-ROW ON DESKTOP, 2x2 ON MOBILE) ───
  quickActionsGridDesktop: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  quickActionsGridMobile: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
    width: '100%',
  },
  actionCardDesktop: {
    flex: 1,
    minWidth: 0,
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  actionCardMobile: {
    width: '48.5%',
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  actionIconBox: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  actionTitle: {
    fontSize: 12.5,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  actionSub: {
    fontSize: 10.5,
    color: colors.textMuted,
    marginTop: 2,
  },
});